#ifndef _MAPCACHE_VERSION_H
#define _MAPCACHE_VERSION_H

#define MAPCACHE_VERSION_MAJOR 1
#define MAPCACHE_VERSION_MINOR 9
#define MAPCACHE_VERSION_REV 0
#define MAPCACHE_VERSION "1.9dev"
#define MAPCACHE_VERSION_NUM  10900 

#endif

